# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProduct = channel.unary_unary(
                '/product.Product/CreateProduct',
                request_serializer=product__pb2.ProductItem.SerializeToString,
                response_deserializer=product__pb2.ProductItem.FromString,
                _registered_method=True)
        self.ReadProduct = channel.unary_unary(
                '/product.Product/ReadProduct',
                request_serializer=product__pb2.ProductId.SerializeToString,
                response_deserializer=product__pb2.ProductItem.FromString,
                _registered_method=True)
        self.ReadProducts = channel.unary_unary(
                '/product.Product/ReadProducts',
                request_serializer=product__pb2.VoidParam.SerializeToString,
                response_deserializer=product__pb2.ProductItems.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/product.Product/UpdateProduct',
                request_serializer=product__pb2.ProductItem.SerializeToString,
                response_deserializer=product__pb2.ProductItem.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/product.Product/DeleteProduct',
                request_serializer=product__pb2.ProductId.SerializeToString,
                response_deserializer=product__pb2.DeleteProductResponse.FromString,
                _registered_method=True)
        self.GenerateProducts = channel.unary_unary(
                '/product.Product/GenerateProducts',
                request_serializer=product__pb2.VoidParam.SerializeToString,
                response_deserializer=product__pb2.GenerateProductsResponse.FromString,
                _registered_method=True)


class ProductServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateProducts(self, request, context):
        """New service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=product__pb2.ProductItem.FromString,
                    response_serializer=product__pb2.ProductItem.SerializeToString,
            ),
            'ReadProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadProduct,
                    request_deserializer=product__pb2.ProductId.FromString,
                    response_serializer=product__pb2.ProductItem.SerializeToString,
            ),
            'ReadProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadProducts,
                    request_deserializer=product__pb2.VoidParam.FromString,
                    response_serializer=product__pb2.ProductItems.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=product__pb2.ProductItem.FromString,
                    response_serializer=product__pb2.ProductItem.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=product__pb2.ProductId.FromString,
                    response_serializer=product__pb2.DeleteProductResponse.SerializeToString,
            ),
            'GenerateProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProducts,
                    request_deserializer=product__pb2.VoidParam.FromString,
                    response_serializer=product__pb2.GenerateProductsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.Product', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.Product', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Product(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.Product/CreateProduct',
            product__pb2.ProductItem.SerializeToString,
            product__pb2.ProductItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.Product/ReadProduct',
            product__pb2.ProductId.SerializeToString,
            product__pb2.ProductItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.Product/ReadProducts',
            product__pb2.VoidParam.SerializeToString,
            product__pb2.ProductItems.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.Product/UpdateProduct',
            product__pb2.ProductItem.SerializeToString,
            product__pb2.ProductItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.Product/DeleteProduct',
            product__pb2.ProductId.SerializeToString,
            product__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.Product/GenerateProducts',
            product__pb2.VoidParam.SerializeToString,
            product__pb2.GenerateProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
