# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x0b\n\tVoidParam\"\x17\n\tProductId\x12\n\n\x02id\x18\x01 \x01(\x05\"p\n\x0bProductItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12#\n\x08\x63\x61tegory\x18\x05 \x01(\x0e\x32\x11.product.Category\"6\n\x0cProductItems\x12&\n\x08products\x18\x01 \x03(\x0b\x32\x14.product.ProductItem\"(\n\x15\x44\x65leteProductResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"+\n\x18GenerateProductsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t*\xa6\x01\n\x08\x43\x61tegory\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nSMARTPHONE\x10\x01\x12\n\n\x06\x43\x41MERA\x10\x02\x12\x0b\n\x07LAPTOPS\x10\x03\x12\x0e\n\nHEADPHONES\x10\x04\x12\x0c\n\x08\x43HARGERS\x10\x05\x12\x0c\n\x08SPEAKERS\x10\x06\x12\x0f\n\x0bTELEVISIONS\x10\x07\x12\n\n\x06MODEMS\x10\x08\x12\r\n\tKEYBOARDs\x10\t\x12\x0f\n\x0bMICROPHONES\x10\n2\x87\x03\n\x07Product\x12;\n\rCreateProduct\x12\x14.product.ProductItem\x1a\x14.product.ProductItem\x12\x37\n\x0bReadProduct\x12\x12.product.ProductId\x1a\x14.product.ProductItem\x12\x39\n\x0cReadProducts\x12\x12.product.VoidParam\x1a\x15.product.ProductItems\x12;\n\rUpdateProduct\x12\x14.product.ProductItem\x1a\x14.product.ProductItem\x12\x43\n\rDeleteProduct\x12\x12.product.ProductId\x1a\x1e.product.DeleteProductResponse\x12I\n\x10GenerateProducts\x12\x12.product.VoidParam\x1a!.product.GenerateProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORY']._serialized_start=322
  _globals['_CATEGORY']._serialized_end=488
  _globals['_VOIDPARAM']._serialized_start=26
  _globals['_VOIDPARAM']._serialized_end=37
  _globals['_PRODUCTID']._serialized_start=39
  _globals['_PRODUCTID']._serialized_end=62
  _globals['_PRODUCTITEM']._serialized_start=64
  _globals['_PRODUCTITEM']._serialized_end=176
  _globals['_PRODUCTITEMS']._serialized_start=178
  _globals['_PRODUCTITEMS']._serialized_end=232
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=234
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=274
  _globals['_GENERATEPRODUCTSRESPONSE']._serialized_start=276
  _globals['_GENERATEPRODUCTSRESPONSE']._serialized_end=319
  _globals['_PRODUCT']._serialized_start=491
  _globals['_PRODUCT']._serialized_end=882
# @@protoc_insertion_point(module_scope)
